--- #YAML:1.0
name: XML-Genx
version: 0.14
author:
  - Dominic Mitchell, E<lt>cpan@happygiraffe.netE<gt>
abstract: Simple, correct XML writer
license: bsd
requires:
  perl: 5.6.1
recommends:
  XML::SAX::Base: 0
provides:
  XML::Genx:
    file: lib/XML/Genx.pm
    version: 0.14
  XML::Genx::Constants:
    file: lib/XML/Genx/Constants.pm
    version: 0.14
  XML::Genx::SAXWriter:
    file: lib/XML/Genx/SAXWriter.pm
    version: 0.14
  XML::Genx::Simple:
    file: lib/XML/Genx/Simple.pm
    version: 0.14
generated_by: Module::Build version 0.2608
